/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:2591be8c-d058-43d3-90da-09f53247227a",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_ZGJZJdy3o",
    "aws_user_pools_web_client_id": "2lp5v456b2b1fgs764blpui2eq",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amw-user-uploadsf103e-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-2",
    "aws_appsync_graphqlEndpoint": "https://vrettj7sfvcxzm4jx23kwdga2u.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7gcir42rvjbupl7rcv4v4kqm4a",
    "Auth": {
        "region": "ap-southeast-2",
        "userPoolId": "ap-southeast-2_3ukQRLsbT",
        "userPoolWebClientId": "vndslp6gpngn38vjm9prjiib6",
        "mandatorySignIn": true
    },
    "Storage": {
        "AWSS3": {
            "bucket": "amw-storage-bucket",
            "region": "ap-southeast-2"
        }
    },
    "API": {
        "GraphQL": {
            "endpoint": "https://hw5ia7ty7zbqtns66kb65wbvga.appsync-api.ap-southeast-2.amazonaws.com/graphql",
            "region": "ap-southeast-2",
            "authMode": "AMAZON_COGNITO_USER_POOLS",
            "additionalAuthModes": [
                {
                    "authMode": "AWS_IAM"
                },
                {
                    "authMode": "API_KEY",
                    "apiKey": "da2-uzra7gvjvfc4fke6angzxdkfi4"
                }
            ]
        }
    }
};


export default awsmobile;
